services:
  binance-bot:
    image: ghcr.io/iliyian/binance-bot:latest
    container_name: binance-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
